import test from "node:test";
import assert from "node:assert/strict";
import { sha256Text } from "../src/canonical.mjs";
import { Q64_MAX_RAW,Q64Error,Q_ONE,qAdd,qDiv,qFromInt,qFromRatio,qMul,qParse,qSerialize,qSub } from "../src/q64.mjs";
import * as F from "../src/fabric.mjs";

const Q=(n,d=1n)=>qFromRatio(BigInt(n),BigInt(d));
const baseline={id:"openai-primary",provider:"openai",schema_version:"7.0.0",supported_modes:["fast","strict","audit"],deterministic_capable:false,critical:true,max_context_raw:qSerialize(qFromInt(8192n))};
const candidate={...baseline,id:"gemini-candidate",provider:"gemini"};
const goodEvidence={id:"E1",source:"shadow",source_type:"INTERNAL",content:"ok",hash:"a".repeat(64),confidence_raw:qSerialize(Q_ONE),verified:true,collected_at:"2026-10-05T00:00:00Z",normalization_version:"1"};

test("20 system registry is complete and distinct",()=>{assert.equal(F.AMCF_SYSTEMS.length,20);assert.equal(new Set(F.AMCF_SYSTEMS).size,20)});
test("S01 fingerprints deterministically across mode order",()=>{const a=F.s01Fingerprint(candidate),b=F.s01Fingerprint({...candidate,supported_modes:["audit","fast","strict"]});assert.equal(a.status,"PASS");assert.equal(a.evidence.fingerprint,b.evidence.fingerprint)});
test("S02 accepts complete adapter metadata",()=>assert.equal(F.s02AdapterContract(candidate).status,"PASS"));
test("S02 freezes malformed adapter",()=>assert.equal(F.s02AdapterContract({...candidate,id:""}).status,"FREEZE"));
test("S03 passes equal schema",()=>assert.equal(F.s03SchemaEvolution(baseline,candidate).status,"PASS"));
test("S03 defers unproven schema change",()=>assert.equal(F.s03SchemaEvolution(baseline,{...candidate,schema_version:"8.0.0"}).status,"DEFER"));
test("S03 passes explicit compatibility edge",()=>assert.equal(F.s03SchemaEvolution(baseline,{...candidate,schema_version:"7.1.0"},["7.0.0->7.1.0"]).status,"PASS"));
test("S04 rejects missing mode",()=>assert.equal(F.s04ModeCoverage(baseline,{...candidate,supported_modes:["fast","strict"]}).status,"FAIL"));
test("S04 accepts superset",()=>assert.equal(F.s04ModeCoverage(baseline,{...candidate,supported_modes:["fast","strict","audit","shadow"]}).status,"PASS"));
test("S05 rejects context regression",()=>assert.equal(F.s05ContextCapacity(baseline,{...candidate,max_context_raw:qSerialize(qFromInt(4096n))}).status,"FAIL"));
test("S05 accepts equal capacity",()=>assert.equal(F.s05ContextCapacity(baseline,candidate).status,"PASS"));
test("S06 maps degraded to SHADOW_ONLY",()=>assert.equal(F.s06HealthNormalize({classification:"DEGRADED"}).evidence.normalized,"SHADOW_ONLY"));
test("S06 freezes unknown health",()=>assert.equal(F.s06HealthNormalize({classification:"MAYBE"}).status,"FREEZE"));
test("S07 rejects latency over budget",()=>assert.equal(F.s07LatencyBudget(qSerialize(qFromInt(1200n)),qSerialize(qFromInt(1000n))).status,"FAIL"));
test("S08 computes exact 3/4 reliability",()=>assert.equal(F.s08Reliability(["PASS","PASS","FAIL","PASS"]).evidence.pass_ratio_raw,qSerialize(Q(3,4))));
test("S08 freezes malformed status",()=>assert.equal(F.s08Reliability(["PASS","UNKNOWN"]).status,"FREEZE"));
test("S09 detects monotonic degradation beyond threshold",()=>assert.equal(F.s09DegradationTrend([qSerialize(Q(95,100)),qSerialize(Q(90,100)),qSerialize(Q(70,100))],qSerialize(Q(10,100))).status,"FAIL"));
test("S09 defers too-short window",()=>assert.equal(F.s09DegradationTrend([qSerialize(Q_ONE)],qSerialize(Q(1,10))).status,"DEFER"));
test("S10 golden vectors pass",()=>{const actual="stable";assert.equal(F.s10GoldenVectors([{id:"g1",actual,expected_hash:sha256Text(actual)}]).status,"PASS")});
test("S10 golden vectors fail mismatch",()=>assert.equal(F.s10GoldenVectors([{id:"g1",actual:"a",expected_hash:sha256Text("b")}]).status,"FAIL"));
test("S11 replay deterministic despite object key order",()=>assert.equal(F.s11Replay([{a:"x",b:"y"},{b:"y",a:"x"}]).status,"PASS"));
test("S11 catches replay drift",()=>assert.equal(F.s11Replay([{a:"x"},{a:"y"}]).status,"FAIL"));
test("S12 accepts complete evidence contract",()=>assert.equal(F.s12EvidenceContract([goodEvidence]).status,"PASS"));
test("S12 rejects missing provenance",()=>assert.equal(F.s12EvidenceContract([{...goodEvidence,source:undefined}]).status,"FAIL"));
test("S13 catches hidden FREEZE",()=>assert.equal(F.s13FreezeSemantics([{id:"f1",expected:"FREEZE",actual:"ALLOW"}]).status,"FAIL"));
test("S13 accepts preserved FREEZE",()=>assert.equal(F.s13FreezeSemantics([{id:"f1",expected:"FREEZE",actual:"FREEZE"}]).status,"PASS"));
test("S14 quorum viable using Q64 threshold",()=>assert.equal(F.s14QuorumViability(["AVAILABLE","AVAILABLE","EXCLUDED"],qSerialize(qFromInt(2n))).status,"PASS"));
test("S14 rejects low quorum",()=>assert.equal(F.s14QuorumViability(["AVAILABLE","EXCLUDED"],qSerialize(qFromInt(2n))).status,"FAIL"));
test("S15 provider diversity passes",()=>assert.equal(F.s15Diversity([{provider:"openai"},{provider:"gemini"}],qSerialize(qFromInt(2n))).status,"PASS"));
test("S15 correlated single-provider set fails",()=>assert.equal(F.s15Diversity([{provider:"openai"},{provider:"openai"}],qSerialize(qFromInt(2n))).status,"FAIL"));
test("S16 shadow routing exact parity passes",()=>assert.equal(F.s16ShadowRouting([{id:"x",baseline_hash:"a",candidate_hash:"a",evidence_ok:true,freeze_ok:true}],qSerialize(Q_ONE)).status,"PASS"));
test("S16 below threshold fails",()=>assert.equal(F.s16ShadowRouting([{id:"x",baseline_hash:"a",candidate_hash:"b",evidence_ok:true,freeze_ok:true}],qSerialize(Q_ONE)).status,"FAIL"));
test("S17 stale pins defer",()=>assert.equal(F.s17CutoverReadiness([{system:"S01",status:"PASS"}],{nexy:"a",spec:"b"},{nexy:"c",spec:"b"}).status,"DEFER"));
test("S17 all pass and pins stable passes",()=>assert.equal(F.s17CutoverReadiness([{system:"S01",status:"PASS"}],{nexy:"a",spec:"b"},{nexy:"a",spec:"b"}).status,"PASS"));
test("S18 rollback capsule deterministic across topology order",()=>{const a=[{id:"b",provider:"g",fingerprint:"2"},{id:"a",provider:"o",fingerprint:"1"}];const b=[a[1],a[0]];assert.equal(F.s18RollbackCapsule(a,{nexy:"n",spec:"s"}).evidence.rollback_hash,F.s18RollbackCapsule(b,{nexy:"n",spec:"s"}).evidence.rollback_hash)});
test("S19 catches reliability drift",()=>assert.equal(F.s19PostSwapDrift({reliability_raw:qSerialize(Q(8,10)),evidence_ratio_raw:qSerialize(Q_ONE),shadow_parity_raw:qSerialize(Q_ONE),latency_raw:qSerialize(qFromInt(10n))},{min_reliability_raw:qSerialize(Q(9,10)),min_evidence_ratio_raw:qSerialize(Q(9,10)),min_shadow_parity_raw:qSerialize(Q(9,10)),max_latency_raw:qSerialize(qFromInt(20n))}).status,"FAIL"));
test("S19 accepts in-policy observations",()=>assert.equal(F.s19PostSwapDrift({reliability_raw:qSerialize(Q(95,100)),evidence_ratio_raw:qSerialize(Q_ONE),shadow_parity_raw:qSerialize(Q_ONE),latency_raw:qSerialize(qFromInt(10n))},{min_reliability_raw:qSerialize(Q(9,10)),min_evidence_ratio_raw:qSerialize(Q(9,10)),min_shadow_parity_raw:qSerialize(Q(9,10)),max_latency_raw:qSerialize(qFromInt(20n))}).status,"PASS"));
test("S20 requires 19 upstream systems",()=>assert.equal(F.s20Orchestrate([]).verdict,undefined));
test("S20 rejects proven blocker",()=>{const r=Array.from({length:19},(_,i)=>({system:`S${String(i+1).padStart(2,"0")}`,status:"PASS"}));r[5]={system:"S06",status:"FAIL",reason:"x"};assert.equal(F.s20Orchestrate(r).verdict,"REJECT_CANDIDATE")});
test("S20 defers unresolved evidence",()=>{const r=Array.from({length:19},(_,i)=>({system:`S${String(i+1).padStart(2,"0")}`,status:"PASS"}));r[2]={system:"S03",status:"DEFER"};assert.equal(F.s20Orchestrate(r).verdict,"DEFER")});
test("S20 produces candidate only with all 19 PASS and cannot promote",()=>{const r=Array.from({length:19},(_,i)=>({system:`S${String(i+1).padStart(2,"0")}`,status:"PASS"}));const v=F.s20Orchestrate(r);assert.equal(v.verdict,"PROMOTION_CANDIDATE");assert.match(v.authority,/NO_PROMOTION_API/);assert.notEqual(v.verdict,"PROMOTED")});

test("Q64 serialization roundtrip",()=>{const x=Q(-3,2);assert.equal(qParse(qSerialize(x)),x)});
test("Q64 multiplication deterministic with representational rounding",()=>assert.equal(qMul(Q(3,2),Q(2,3)),Q_ONE+1n));
test("Q64 division by zero fails closed",()=>assert.throws(()=>qDiv(Q_ONE,0n),e=>e instanceof Q64Error&&e.code==="Q64_DIV_ZERO"));
test("Q64 overflow fails closed",()=>assert.throws(()=>qAdd(Q64_MAX_RAW,1n),e=>e instanceof Q64Error&&e.code==="Q64_OVERFLOW"));
test("Q64 underflow fails closed",()=>assert.throws(()=>qFromRatio(1n,1n<<100n),e=>e instanceof Q64Error&&e.code==="Q64_UNDERFLOW"));
test("Q64 ties round away from zero",()=>{const raw=qFromRatio(1n,1n<<65n);assert.equal(raw,1n);const neg=qFromRatio(-1n,1n<<65n);assert.equal(neg,-1n)});
test("No system exports release/promote mutation function",()=>{for(const k of Object.keys(F))assert.doesNotMatch(k,/^(promote|release|mutateCanon|writeCore)$/i)});
