import { canonicalPretty } from "./canonicalize.mjs";
import { buildExpectedRuntimeSnapshot } from "./audit.mjs";
import { normalizeAndValidateManifest } from "./validate-manifest.mjs";

function pascalToScreaming(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toUpperCase();
}

function jsString(value) {
  return JSON.stringify(value);
}

function rustString(value) {
  return JSON.stringify(value);
}

function enumByName(normalized, name) {
  const enumeration = normalized.enums.find((item) => item.name === name);
  if (!enumeration) throw new Error(`internal enum missing: ${name}`);
  return enumeration;
}

function memberByWire(enumeration, wire) {
  const member = enumeration.members.find((item) => item.wire === wire);
  if (!member) throw new Error(`internal member missing: ${enumeration.name}:${wire}`);
  return member;
}

export function compileTypeScript(inputManifest) {
  const { normalized, semanticFingerprint, manifestFingerprint } = normalizeAndValidateManifest(inputManifest);
  const lines = [
    "// @generated by NEXY Cross-Runtime Contract Forge. DO NOT EDIT BY HAND.",
    `// contract: ${normalized.contractId}@${normalized.contractVersion}`,
    `// semantic-fingerprint: ${semanticFingerprint}`,
    `// manifest-fingerprint: ${manifestFingerprint}`,
    "",
    `export const CONTRACT_ID = ${jsString(normalized.contractId)} as const;`,
    `export const CONTRACT_VERSION = ${jsString(normalized.contractVersion)} as const;`,
    `export const CONTRACT_SEMANTIC_FINGERPRINT = ${jsString(semanticFingerprint)} as const;`,
    `export const CONTRACT_MANIFEST_FINGERPRINT = ${jsString(manifestFingerprint)} as const;`,
    "",
  ];
  for (const enumeration of normalized.enums) {
    lines.push(`export const ${enumeration.name} = {`);
    for (const member of enumeration.members) lines.push(`  ${member.name}: ${jsString(member.wire)},`);
    lines.push(`} as const;`);
    lines.push(`export type ${enumeration.name} = (typeof ${enumeration.name})[keyof typeof ${enumeration.name}];`);
    lines.push(`export const ${enumeration.name}Values = Object.freeze([${enumeration.members.map((m) => jsString(m.wire)).join(", ")}] as const);`);
    lines.push("");
  }
  for (const machine of normalized.stateMachines) {
    const transitionType = `${machine.name}Transition`;
    lines.push(`export interface ${transitionType} {`);
    lines.push(`  readonly from: ${machine.stateEnum};`);
    lines.push(`  readonly event: ${machine.eventEnum};`);
    lines.push(`  readonly to: ${machine.stateEnum};`);
    lines.push(`  readonly actors: readonly ${machine.actorEnum}[];`);
    lines.push(`  readonly guards: readonly string[];`);
    lines.push(`}`);
    lines.push(`export const ${pascalToScreaming(machine.name)}_INITIAL_STATE: ${machine.stateEnum} = ${jsString(machine.initialState)};`);
    lines.push(`export const ${pascalToScreaming(machine.name)}_TERMINAL_STATES = Object.freeze([${machine.terminalStates.map(jsString).join(", ")}] as const);`);
    lines.push(`export const ${pascalToScreaming(machine.name)}_TRANSITIONS: readonly ${transitionType}[] = Object.freeze([`);
    for (const transition of machine.transitions) {
      lines.push(`  Object.freeze({ from: ${jsString(transition.from)}, event: ${jsString(transition.event)}, to: ${jsString(transition.to)}, actors: Object.freeze([${transition.actors.map(jsString).join(", ")}] as const), guards: Object.freeze([${transition.guards.map(jsString).join(", ")}] as const) }),`);
    }
    lines.push(`]);`);
    lines.push(`export function ${machine.name}Next(`);
    lines.push(`  current: ${machine.stateEnum},`);
    lines.push(`  event: ${machine.eventEnum},`);
    lines.push(`  actor: ${machine.actorEnum},`);
    lines.push(`  provenGuards: ReadonlySet<string> = new Set<string>(),`);
    lines.push(`): ${machine.stateEnum} | null {`);
    lines.push(`  const transition = ${pascalToScreaming(machine.name)}_TRANSITIONS.find((candidate) =>`);
    lines.push(`    candidate.from === current && candidate.event === event && candidate.actors.includes(actor),`);
    lines.push(`  );`);
    lines.push(`  if (transition === undefined) return null;`);
    lines.push(`  for (const guard of transition.guards) if (!provenGuards.has(guard)) return null;`);
    lines.push(`  return transition.to;`);
    lines.push(`}`);
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function compileRust(inputManifest) {
  const { normalized, semanticFingerprint, manifestFingerprint } = normalizeAndValidateManifest(inputManifest);
  const lines = [
    "// @generated by NEXY Cross-Runtime Contract Forge. DO NOT EDIT BY HAND.",
    `// contract: ${normalized.contractId}@${normalized.contractVersion}`,
    `// semantic-fingerprint: ${semanticFingerprint}`,
    `// manifest-fingerprint: ${manifestFingerprint}`,
    "#![no_std]",
    "",
    `pub const CONTRACT_ID: &str = ${rustString(normalized.contractId)};`,
    `pub const CONTRACT_VERSION: &str = ${rustString(normalized.contractVersion)};`,
    `pub const CONTRACT_SEMANTIC_FINGERPRINT: &str = ${rustString(semanticFingerprint)};`,
    `pub const CONTRACT_MANIFEST_FINGERPRINT: &str = ${rustString(manifestFingerprint)};`,
    "",
  ];
  for (const enumeration of normalized.enums) {
    lines.push("#[derive(Debug, Clone, Copy, PartialEq, Eq)]");
    lines.push(`pub enum ${enumeration.name} {`);
    for (const member of enumeration.members) lines.push(`    ${member.name},`);
    lines.push("}");
    lines.push(`impl ${enumeration.name} {`);
    lines.push("    pub const fn as_str(self) -> &'static str {");
    lines.push("        match self {");
    for (const member of enumeration.members) lines.push(`            Self::${member.name} => ${rustString(member.wire)},`);
    lines.push("        }");
    lines.push("    }");
    lines.push("    pub fn from_str(value: &str) -> Option<Self> {");
    lines.push("        match value {");
    for (const member of enumeration.members) lines.push(`            ${rustString(member.wire)} => Some(Self::${member.name}),`);
    lines.push("            _ => None,");
    lines.push("        }");
    lines.push("    }");
    lines.push("}");
    lines.push("");
  }
  for (const machine of normalized.stateMachines) {
    const stateEnum = enumByName(normalized, machine.stateEnum);
    const eventEnum = enumByName(normalized, machine.eventEnum);
    const actorEnum = enumByName(normalized, machine.actorEnum);
    const structName = `${machine.name}Transition`;
    const fnName = machine.name.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
    lines.push(`pub struct ${structName} {`);
    lines.push(`    pub from: ${machine.stateEnum},`);
    lines.push(`    pub event: ${machine.eventEnum},`);
    lines.push(`    pub to: ${machine.stateEnum},`);
    lines.push(`    pub actors: &'static [${machine.actorEnum}],`);
    lines.push(`    pub guards: &'static [&'static str],`);
    lines.push("}");
    lines.push(`pub const ${pascalToScreaming(machine.name)}_INITIAL_STATE: ${machine.stateEnum} = ${machine.stateEnum}::${memberByWire(stateEnum, machine.initialState).name};`);
    lines.push(`pub const ${pascalToScreaming(machine.name)}_TERMINAL_STATES: &[${machine.stateEnum}] = &[${machine.terminalStates.map((wire) => `${machine.stateEnum}::${memberByWire(stateEnum, wire).name}`).join(", ")}];`);
    lines.push(`pub const ${pascalToScreaming(machine.name)}_TRANSITIONS: &[${structName}] = &[`);
    for (const transition of machine.transitions) {
      const actors = transition.actors.map((wire) => `${machine.actorEnum}::${memberByWire(actorEnum, wire).name}`).join(", ");
      lines.push(`    ${structName} { from: ${machine.stateEnum}::${memberByWire(stateEnum, transition.from).name}, event: ${machine.eventEnum}::${memberByWire(eventEnum, transition.event).name}, to: ${machine.stateEnum}::${memberByWire(stateEnum, transition.to).name}, actors: &[${actors}], guards: &[${transition.guards.map(rustString).join(", ")}] },`);
    }
    lines.push("];\n");
    lines.push(`pub fn ${fnName}_next(`);
    lines.push(`    current: ${machine.stateEnum},`);
    lines.push(`    event: ${machine.eventEnum},`);
    lines.push(`    actor: ${machine.actorEnum},`);
    lines.push("    guard_proven: fn(&str) -> bool,");
    lines.push(`) -> Option<${machine.stateEnum}> {`);
    lines.push(`    for transition in ${pascalToScreaming(machine.name)}_TRANSITIONS {`);
    lines.push("        if transition.from != current || transition.event != event { continue; }");
    lines.push("        if !transition.actors.iter().any(|candidate| *candidate == actor) { continue; }");
    lines.push("        if !transition.guards.iter().all(|guard| guard_proven(guard)) { return None; }");
    lines.push("        return Some(transition.to);");
    lines.push("    }");
    lines.push("    None");
    lines.push("}");
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

export function buildConformanceFixtures(inputManifest) {
  const { normalized, semanticFingerprint } = normalizeAndValidateManifest(inputManifest);
  const machines = Object.create(null);
  for (const machine of normalized.stateMachines) {
    const positive = [];
    const negative = [];
    for (const transition of machine.transitions) {
      for (const actor of transition.actors) {
        positive.push({
          from: transition.from,
          event: transition.event,
          actor,
          provenGuards: transition.guards,
          expectedTo: transition.to,
        });
      }
      negative.push({
        from: transition.from,
        event: transition.event,
        actor: "__UNAUTHORIZED_ACTOR__",
        provenGuards: transition.guards,
        expectedTo: null,
        reason: "actor_not_in_contract",
      });
      if (transition.guards.length > 0) {
        negative.push({
          from: transition.from,
          event: transition.event,
          actor: transition.actors[0],
          provenGuards: transition.guards.slice(1),
          expectedTo: null,
          reason: "required_guard_missing",
        });
      }
    }
    machines[machine.name] = { positive, negative };
  }
  return {
    fixtureSchemaVersion: 1,
    contractId: normalized.contractId,
    contractVersion: normalized.contractVersion,
    semanticFingerprint,
    machines,
  };
}

export function compileContract(inputManifest) {
  const meta = normalizeAndValidateManifest(inputManifest);
  return {
    normalizedManifest: canonicalPretty(meta.normalized),
    typescript: compileTypeScript(meta.normalized),
    rust: compileRust(meta.normalized),
    runtimeSnapshot: canonicalPretty(buildExpectedRuntimeSnapshot(meta.normalized)),
    fixtures: canonicalPretty(buildConformanceFixtures(meta.normalized)),
    semanticFingerprint: meta.semanticFingerprint,
    manifestFingerprint: meta.manifestFingerprint,
  };
}
