// API Library — curated API data
// tier: free = works at $0 | freemium = free tier, real usage costs | paid = paid product/API required
// auth.t: none | bearer | basic | header (k = header name) | query (key placeholder already in URL)
// cc: ISO-3166 country of the company/org HQ; null = global/community project (🌐)
// ep: sample call — m method, u URL (placeholders in <>), h extra headers, b JSON body; null = see docs
const CATS = {
  ai:     { label: "AI & LLM",           icon: "🤖" },
  search: { label: "Search & News",      icon: "🔍" },
  geo:    { label: "Maps & Geo",         icon: "🗺️" },
  wx:     { label: "Weather",            icon: "🌦️" },
  fin:    { label: "Finance & Crypto",   icon: "📈" },
  pay:    { label: "Payments",           icon: "💳" },
  comm:   { label: "Email & Messaging",  icon: "💬" },
  social: { label: "Social & Content",   icon: "📱" },
  media:  { label: "Images & Media",     icon: "🖼️" },
  dev:    { label: "Dev & Code",         icon: "🛠️" },
  data:   { label: "Open Data & Science",icon: "🔬" },
  store:  { label: "Storage & BaaS",     icon: "🗄️" },
  util:   { label: "Utilities",          icon: "🧰" },
  india:  { label: "India",              icon: "<img class=\"flimg\" src=\"https://flagcdn.com/16x12/in.png\" width=\"16\" height=\"12\" alt=\"IN\">" }
};

const APIS = [
  // ---------- AI & LLM ----------
  { id:"anthropic", n:"Anthropic Claude", cat:"ai", cc:"US", tier:"paid",
    auth:{t:"header", k:"x-api-key"}, quota:"No free tier — pay per token",
    use:"Frontier LLM — Claude models for chat, agents, coding, vision and tool use.",
    ep:{m:"POST", u:"https://api.anthropic.com/v1/messages", h:{"anthropic-version":"2023-06-01","content-type":"application/json"}, b:{model:"claude-sonnet-5",max_tokens:256,messages:[{role:"user",content:"Hello"}]}},
    docs:"https://docs.anthropic.com" },
  { id:"openai", n:"OpenAI", cat:"ai", cc:"US", tier:"paid",
    auth:{t:"bearer"}, quota:"No free tier — pay per token",
    use:"GPT models, embeddings, image generation and speech APIs.",
    ep:{m:"POST", u:"https://api.openai.com/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"gpt-5.2",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://platform.openai.com/docs" },
  { id:"gemini", n:"Google Gemini", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free tier: rate-limited requests/day on Flash models",
    use:"Gemini multimodal models — long context, vision, cheap Flash tier.",
    ep:{m:"POST", u:"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=<YOUR_KEY>", h:{"content-type":"application/json"}, b:{contents:[{parts:[{text:"Hello"}]}]}},
    docs:"https://ai.google.dev/gemini-api/docs" },
  { id:"mistral", n:"Mistral AI", cat:"ai", cc:"FR", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free tier on La Plateforme (rate-limited)",
    use:"Open-weight European LLMs — chat, code (Codestral), embeddings.",
    ep:{m:"POST", u:"https://api.mistral.ai/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"mistral-small-latest",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://docs.mistral.ai" },
  { id:"cohere", n:"Cohere", cat:"ai", cc:"CA", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free trial keys, rate-limited",
    use:"Enterprise LLMs — Command models, best-in-class rerank and embeddings for RAG.",
    ep:{m:"POST", u:"https://api.cohere.com/v2/chat", h:{"content-type":"application/json"}, b:{model:"command-r",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://docs.cohere.com" },
  { id:"groq", n:"Groq", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Generous free tier — fastest inference (LPU)",
    use:"Ultra-fast open-model inference — Llama, DeepSeek, Whisper at 100s of tok/s.",
    ep:{m:"POST", u:"https://api.groq.com/openai/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"llama-3.3-70b-versatile",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://console.groq.com/docs" },
  { id:"openrouter", n:"OpenRouter", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Some :free models; else pay-per-token across 400+ models",
    use:"One API for every LLM — route across OpenAI/Anthropic/Google/open models.",
    ep:{m:"POST", u:"https://openrouter.ai/api/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"meta-llama/llama-3.3-70b-instruct:free",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://openrouter.ai/docs" },
  { id:"together", n:"Together AI", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free starting credits",
    use:"Open-model hosting — Llama, Qwen, FLUX at low cost with fine-tuning.",
    ep:{m:"POST", u:"https://api.together.xyz/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"meta-llama/Llama-3.3-70B-Instruct-Turbo",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://docs.together.ai" },
  { id:"huggingface", n:"Hugging Face Inference", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free tier with monthly credits",
    use:"Run thousands of open models — text, vision, audio — via one inference API.",
    ep:{m:"POST", u:"https://router.huggingface.co/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"meta-llama/Llama-3.3-70B-Instruct",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://huggingface.co/docs/inference-providers" },
  { id:"replicate", n:"Replicate", cat:"ai", cc:"US", tier:"paid",
    auth:{t:"bearer"}, quota:"Pay per second of compute",
    use:"Run any published model — image gen, video, upscaling — by API.",
    ep:{m:"POST", u:"https://api.replicate.com/v1/predictions", h:{"content-type":"application/json"}, b:{version:"<model-version>",input:{prompt:"a cat astronaut"}}},
    docs:"https://replicate.com/docs" },
  { id:"elevenlabs", n:"ElevenLabs", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"header", k:"xi-api-key"}, quota:"Free: 10k chars/month TTS",
    use:"Best-in-class text-to-speech, voice cloning and dubbing.",
    ep:{m:"POST", u:"https://api.elevenlabs.io/v1/text-to-speech/<voice_id>", h:{"content-type":"application/json"}, b:{text:"Hello world",model_id:"eleven_multilingual_v2"}},
    docs:"https://elevenlabs.io/docs" },
  { id:"deepgram", n:"Deepgram", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"header", k:"Authorization"}, quota:"$200 free credit",
    use:"Fast, accurate speech-to-text and voice agents (use header value: Token YOUR_KEY).",
    ep:{m:"POST", u:"https://api.deepgram.com/v1/listen?model=nova-3", h:{"content-type":"application/json"}, b:{url:"https://dpgr.am/spacewalk.wav"}},
    docs:"https://developers.deepgram.com" },
  { id:"assemblyai", n:"AssemblyAI", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"header", k:"authorization"}, quota:"Free credits at signup",
    use:"Speech-to-text with speaker labels, summarization and audio intelligence.",
    ep:{m:"POST", u:"https://api.assemblyai.com/v2/transcript", h:{"content-type":"application/json"}, b:{audio_url:"https://example.com/audio.mp3"}},
    docs:"https://www.assemblyai.com/docs" },
  { id:"stability", n:"Stability AI", cat:"ai", cc:"GB", tier:"paid",
    auth:{t:"bearer"}, quota:"Credit-based; small trial credits",
    use:"Stable Diffusion / Stable Image generation and editing endpoints.",
    ep:null,
    docs:"https://platform.stability.ai/docs/api-reference" },
  { id:"fal", n:"fal.ai", cat:"ai", cc:"US", tier:"freemium",
    auth:{t:"header", k:"Authorization"}, quota:"Free credits at signup (header value: Key YOUR_KEY)",
    use:"Fast serverless image/video model inference — FLUX, Kling, LoRAs.",
    ep:null,
    docs:"https://docs.fal.ai" },
  { id:"perplexity", n:"Perplexity Sonar", cat:"ai", cc:"US", tier:"paid",
    auth:{t:"bearer"}, quota:"Pay per request + tokens",
    use:"Search-grounded LLM answers with citations, by API.",
    ep:{m:"POST", u:"https://api.perplexity.ai/chat/completions", h:{"content-type":"application/json"}, b:{model:"sonar",messages:[{role:"user",content:"Latest MCP news"}]}},
    docs:"https://docs.perplexity.ai" },
  { id:"xai", n:"xAI Grok", cat:"ai", cc:"US", tier:"paid",
    auth:{t:"bearer"}, quota:"Pay per token",
    use:"Grok models with live X (Twitter) knowledge.",
    ep:{m:"POST", u:"https://api.x.ai/v1/chat/completions", h:{"content-type":"application/json"}, b:{model:"grok-4",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://docs.x.ai" },
  { id:"deepseek", n:"DeepSeek", cat:"ai", cc:"CN", tier:"paid",
    auth:{t:"bearer"}, quota:"Very cheap per-token pricing",
    use:"Strong open-weight reasoning and chat models at rock-bottom prices.",
    ep:{m:"POST", u:"https://api.deepseek.com/chat/completions", h:{"content-type":"application/json"}, b:{model:"deepseek-chat",messages:[{role:"user",content:"Hello"}]}},
    docs:"https://api-docs.deepseek.com" },

  // ---------- Search & News ----------
  { id:"brave", n:"Brave Search", cat:"search", cc:"US", tier:"freemium",
    auth:{t:"header", k:"X-Subscription-Token"}, quota:"Free: 2,000 queries/month",
    use:"Independent web search index — web, news, images by API.",
    ep:{m:"GET", u:"https://api.search.brave.com/res/v1/web/search?q=mcp+servers"},
    docs:"https://api-dashboard.search.brave.com/app/documentation" },
  { id:"tavily", n:"Tavily", cat:"search", cc:"IL", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free: 1,000 credits/month",
    use:"Search + extract + crawl built for LLM/RAG pipelines.",
    ep:{m:"POST", u:"https://api.tavily.com/search", h:{"content-type":"application/json"}, b:{query:"model context protocol"}},
    docs:"https://docs.tavily.com" },
  { id:"exa", n:"Exa", cat:"search", cc:"US", tier:"freemium",
    auth:{t:"header", k:"x-api-key"}, quota:"Free starting credits",
    use:"Neural web search — find pages by meaning, get clean contents.",
    ep:{m:"POST", u:"https://api.exa.ai/search", h:{"content-type":"application/json"}, b:{query:"best MCP servers",numResults:5}},
    docs:"https://docs.exa.ai" },
  { id:"serpapi", n:"SerpApi", cat:"search", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 100 searches/month",
    use:"Structured Google/Bing/Maps/Scholar results as JSON.",
    ep:{m:"GET", u:"https://serpapi.com/search.json?q=coffee&api_key=<YOUR_KEY>"},
    docs:"https://serpapi.com/search-api" },
  { id:"newsapi", n:"NewsAPI.org", cat:"search", cc:"GB", tier:"freemium",
    auth:{t:"query"}, quota:"Free dev tier: 100 req/day, 24h delay",
    use:"Headlines and article search from 150k+ news sources.",
    ep:{m:"GET", u:"https://newsapi.org/v2/top-headlines?country=us&apiKey=<YOUR_KEY>"},
    docs:"https://newsapi.org/docs" },
  { id:"gnews", n:"GNews", cat:"search", cc:"FR", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 100 req/day",
    use:"Google-News-style article search JSON API.",
    ep:{m:"GET", u:"https://gnews.io/api/v4/search?q=ai&apikey=<YOUR_KEY>"},
    docs:"https://gnews.io/docs/v4" },
  { id:"wikipedia", n:"Wikipedia REST", cat:"search", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free — fair use",
    use:"Page summaries, search and content from Wikipedia.",
    ep:{m:"GET", u:"https://en.wikipedia.org/api/rest_v1/page/summary/Model_Context_Protocol"},
    docs:"https://en.wikipedia.org/api/rest_v1/" },
  { id:"wolfram", n:"Wolfram|Alpha", cat:"search", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 2,000 calls/month",
    use:"Computational answers — math, units, science facts as short text.",
    ep:{m:"GET", u:"https://api.wolframalpha.com/v1/result?appid=<YOUR_KEY>&i=integrate+x%5E2"},
    docs:"https://products.wolframalpha.com/api" },
  { id:"hackernews", n:"Hacker News", cat:"search", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Stories, comments and top lists from HN via Firebase.",
    ep:{m:"GET", u:"https://hacker-news.firebaseio.com/v0/topstories.json"},
    docs:"https://github.com/HackerNews/API" },

  // ---------- Maps & Geo ----------
  { id:"gmaps", n:"Google Maps Platform", cat:"geo", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Monthly free usage caps per API",
    use:"Geocoding, directions, places, distance matrix — the industry default.",
    ep:{m:"GET", u:"https://maps.googleapis.com/maps/api/geocode/json?address=Kolkata&key=<YOUR_KEY>"},
    docs:"https://developers.google.com/maps" },
  { id:"mapbox", n:"Mapbox", cat:"geo", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 100k geocodes/month",
    use:"Beautiful vector maps, geocoding, navigation SDKs.",
    ep:{m:"GET", u:"https://api.mapbox.com/geocoding/v5/mapbox.places/Kolkata.json?access_token=<YOUR_KEY>"},
    docs:"https://docs.mapbox.com/api" },
  { id:"nominatim", n:"OSM Nominatim", cat:"geo", cc:"GB", tier:"free",
    auth:{t:"none"}, quota:"Free — 1 req/sec, set a User-Agent",
    use:"OpenStreetMap geocoding — address ⇄ coordinates, no key.",
    ep:{m:"GET", u:"https://nominatim.openstreetmap.org/search?q=Kolkata&format=json", h:{"User-Agent":"my-app/1.0"}},
    docs:"https://nominatim.org/release-docs/latest/api/Overview/" },
  { id:"opencage", n:"OpenCage", cat:"geo", cc:"DE", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 2,500 req/day",
    use:"Geocoding aggregator over open data with clean licensing.",
    ep:{m:"GET", u:"https://api.opencagedata.com/geocode/v1/json?q=Kolkata&key=<YOUR_KEY>"},
    docs:"https://opencagedata.com/api" },
  { id:"here", n:"HERE", cat:"geo", cc:"NL", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 250k transactions/month",
    use:"Enterprise maps — routing, geocoding, traffic, EV routing.",
    ep:null,
    docs:"https://www.here.com/docs" },
  { id:"ipinfo", n:"IPinfo", cat:"geo", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 50k lookups/month",
    use:"IP → location, ASN, company; privacy/VPN detection.",
    ep:{m:"GET", u:"https://ipinfo.io/8.8.8.8?token=<YOUR_KEY>"},
    docs:"https://ipinfo.io/developers" },
  { id:"ipapi", n:"ip-api.com", cat:"geo", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free: 45 req/min (non-commercial, HTTP only)",
    use:"Zero-setup IP geolocation JSON.",
    ep:{m:"GET", u:"http://ip-api.com/json/8.8.8.8"},
    docs:"https://ip-api.com/docs" },
  { id:"restcountries", n:"REST Countries", cat:"geo", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Country facts — flags, currencies, languages, borders.",
    ep:{m:"GET", u:"https://restcountries.com/v3.1/name/india"},
    docs:"https://restcountries.com" },

  // ---------- Weather ----------
  { id:"openmeteo", n:"Open-Meteo", cat:"wx", cc:"DE", tier:"free",
    auth:{t:"none"}, quota:"Free for non-commercial, no key",
    use:"Forecasts, history and air quality — the best free weather API.",
    ep:{m:"GET", u:"https://api.open-meteo.com/v1/forecast?latitude=22.57&longitude=88.36&hourly=temperature_2m"},
    docs:"https://open-meteo.com/en/docs" },
  { id:"openweathermap", n:"OpenWeatherMap", cat:"wx", cc:"GB", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 1,000 calls/day",
    use:"Current weather, forecasts and historical data worldwide.",
    ep:{m:"GET", u:"https://api.openweathermap.org/data/2.5/weather?q=Kolkata&appid=<YOUR_KEY>"},
    docs:"https://openweathermap.org/api" },
  { id:"weatherapi", n:"WeatherAPI.com", cat:"wx", cc:null, tier:"freemium",
    auth:{t:"query"}, quota:"Free: 1M calls/month",
    use:"Realtime + forecast + astronomy + sports weather JSON.",
    ep:{m:"GET", u:"https://api.weatherapi.com/v1/current.json?key=<YOUR_KEY>&q=Kolkata"},
    docs:"https://www.weatherapi.com/docs/" },
  { id:"visualcrossing", n:"Visual Crossing", cat:"wx", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 1,000 records/day",
    use:"Historical weather + timeline forecasts in one endpoint.",
    ep:{m:"GET", u:"https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Kolkata?key=<YOUR_KEY>"},
    docs:"https://www.visualcrossing.com/resources/documentation/weather-api/timeline-weather-api/" },
  { id:"nws", n:"US National Weather Service", cat:"wx", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free (US coverage), no key",
    use:"Official US forecasts, alerts and observations.",
    ep:{m:"GET", u:"https://api.weather.gov/points/39.7456,-97.0892"},
    docs:"https://www.weather.gov/documentation/services-web-api" },

  // ---------- Finance & Crypto ----------
  { id:"coingecko", n:"CoinGecko", cat:"fin", cc:"SG", tier:"freemium",
    auth:{t:"header", k:"x-cg-demo-api-key"}, quota:"Free demo: ~30 calls/min",
    use:"Crypto prices, market caps and metadata for 15k+ coins.",
    ep:{m:"GET", u:"https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd"},
    docs:"https://docs.coingecko.com" },
  { id:"coinmarketcap", n:"CoinMarketCap", cat:"fin", cc:"US", tier:"freemium",
    auth:{t:"header", k:"X-CMC_PRO_API_KEY"}, quota:"Free basic: 10k credits/month",
    use:"Crypto listings, quotes and global market metrics.",
    ep:{m:"GET", u:"https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?limit=10"},
    docs:"https://coinmarketcap.com/api/documentation/v1/" },
  { id:"alphavantage", n:"Alpha Vantage", cat:"fin", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 25 req/day",
    use:"Stocks, forex, crypto time series and 50+ technical indicators.",
    ep:{m:"GET", u:"https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=IBM&apikey=<YOUR_KEY>"},
    docs:"https://www.alphavantage.co/documentation/" },
  { id:"finnhub", n:"Finnhub", cat:"fin", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 60 calls/min",
    use:"Real-time stock quotes, company news and fundamentals.",
    ep:{m:"GET", u:"https://finnhub.io/api/v1/quote?symbol=AAPL&token=<YOUR_KEY>"},
    docs:"https://finnhub.io/docs/api" },
  { id:"massive", n:"Massive (ex Polygon.io)", cat:"fin", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free: 5 calls/min, EOD data",
    use:"Market data — stocks, options, forex, crypto aggregates.",
    ep:{m:"GET", u:"https://api.polygon.io/v2/aggs/ticker/AAPL/prev?apiKey=<YOUR_KEY>"},
    docs:"https://polygon.io/docs" },
  { id:"frankfurter", n:"Frankfurter", cat:"fin", cc:"DE", tier:"free",
    auth:{t:"none"}, quota:"Free, no key — ECB rates",
    use:"Currency exchange rates, current and historical.",
    ep:{m:"GET", u:"https://api.frankfurter.dev/v1/latest?base=USD"},
    docs:"https://frankfurter.dev" },
  { id:"exchangerateapi", n:"ExchangeRate-API", cat:"fin", cc:null, tier:"freemium",
    auth:{t:"query"}, quota:"Free: 1,500 req/month",
    use:"Simple currency conversion rates for 160+ currencies.",
    ep:{m:"GET", u:"https://v6.exchangerate-api.com/v6/<YOUR_KEY>/latest/USD"},
    docs:"https://www.exchangerate-api.com/docs/overview" },
  { id:"binance", n:"Binance", cat:"fin", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Public market data free, no key",
    use:"Live crypto tickers, order books and klines from the largest exchange.",
    ep:{m:"GET", u:"https://api.binance.com/api/v3/ticker/price?symbol=BTCUSDT"},
    docs:"https://developers.binance.com/docs/binance-spot-api-docs" },

  // ---------- Payments ----------
  { id:"stripe", n:"Stripe", cat:"pay", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free to integrate — fees per transaction",
    use:"Payments, subscriptions, invoicing, payment links — dev-first.",
    ep:{m:"GET", u:"https://api.stripe.com/v1/customers?limit=3"},
    docs:"https://docs.stripe.com/api" },
  { id:"paypal", n:"PayPal", cat:"pay", cc:"US", tier:"freemium",
    auth:{t:"basic"}, quota:"Free to integrate — fees per transaction",
    use:"Orders, subscriptions and payouts (OAuth token via client_id:secret).",
    ep:{m:"POST", u:"https://api-m.sandbox.paypal.com/v1/oauth2/token", h:{"content-type":"application/x-www-form-urlencoded"}, b:"grant_type=client_credentials"},
    docs:"https://developer.paypal.com/api/rest/" },
  { id:"squarepay", n:"Square", cat:"pay", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free sandbox — fees per transaction",
    use:"In-person + online payments, catalog, customers.",
    ep:{m:"GET", u:"https://connect.squareup.com/v2/locations"},
    docs:"https://developer.squareup.com/reference/square" },
  { id:"plaid", n:"Plaid", cat:"pay", cc:"US", tier:"freemium",
    auth:{t:"none"}, quota:"Free sandbox; paid production",
    use:"Bank account linking, balances and transactions (client_id + secret in body).",
    ep:{m:"POST", u:"https://sandbox.plaid.com/link/token/create", h:{"content-type":"application/json"}, b:{client_id:"<CLIENT_ID>",secret:"<SECRET>",user:{client_user_id:"u1"},client_name:"MyApp",products:["transactions"],country_codes:["US"],language:"en"}},
    docs:"https://plaid.com/docs/api/" },
  { id:"wise", n:"Wise", cat:"pay", cc:"GB", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free sandbox; fees per transfer",
    use:"Cross-border transfers, multi-currency accounts, live FX rates.",
    ep:null,
    docs:"https://docs.wise.com" },

  // ---------- Email & Messaging ----------
  { id:"twilio", n:"Twilio", cat:"comm", cc:"US", tier:"paid",
    auth:{t:"basic"}, quota:"Trial credit; then pay per message/call",
    use:"SMS, voice, WhatsApp and verification at global scale.",
    ep:{m:"POST", u:"https://api.twilio.com/2010-04-01/Accounts/<ACCOUNT_SID>/Messages.json", h:{"content-type":"application/x-www-form-urlencoded"}, b:"To=+15558675310&From=+15017122661&Body=Hi"},
    docs:"https://www.twilio.com/docs" },
  { id:"sendgrid", n:"SendGrid", cat:"comm", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free: 100 emails/day",
    use:"Transactional + marketing email with templates and analytics.",
    ep:{m:"POST", u:"https://api.sendgrid.com/v3/mail/send", h:{"content-type":"application/json"}, b:{personalizations:[{to:[{email:"to@example.com"}]}],from:{email:"me@example.com"},subject:"Hi",content:[{type:"text/plain",value:"Hello"}]}},
    docs:"https://www.twilio.com/docs/sendgrid/api-reference" },
  { id:"resend", n:"Resend", cat:"comm", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free: 3,000 emails/month",
    use:"Modern email API for developers — React Email templates.",
    ep:{m:"POST", u:"https://api.resend.com/emails", h:{"content-type":"application/json"}, b:{from:"you@yourdomain.com",to:["to@example.com"],subject:"Hi",text:"Hello"}},
    docs:"https://resend.com/docs" },
  { id:"mailgun", n:"Mailgun", cat:"comm", cc:"US", tier:"freemium",
    auth:{t:"basic"}, quota:"Free trial; then paid plans",
    use:"Email sending + validation with strong deliverability tooling (user: api).",
    ep:{m:"POST", u:"https://api.mailgun.net/v3/<YOUR_DOMAIN>/messages", h:{"content-type":"application/x-www-form-urlencoded"}, b:"from=me@example.com&to=to@example.com&subject=Hi&text=Hello"},
    docs:"https://documentation.mailgun.com" },
  { id:"postmark", n:"Postmark", cat:"comm", cc:"US", tier:"freemium",
    auth:{t:"header", k:"X-Postmark-Server-Token"}, quota:"Free: 100 emails/month",
    use:"Fast transactional email famous for inbox placement.",
    ep:{m:"POST", u:"https://api.postmarkapp.com/email", h:{"content-type":"application/json"}, b:{From:"me@example.com",To:"to@example.com",Subject:"Hi",TextBody:"Hello"}},
    docs:"https://postmarkapp.com/developer" },
  { id:"telegram", n:"Telegram Bot API", cat:"comm", cc:"AE", tier:"free",
    auth:{t:"none"}, quota:"Free — token in URL",
    use:"Build bots — send messages, media, keyboards, payments.",
    ep:{m:"GET", u:"https://api.telegram.org/bot<YOUR_TOKEN>/sendMessage?chat_id=<CHAT_ID>&text=Hello"},
    docs:"https://core.telegram.org/bots/api" },
  { id:"discord", n:"Discord", cat:"comm", cc:"US", tier:"free",
    auth:{t:"header", k:"Authorization"}, quota:"Free (header value: Bot YOUR_TOKEN)",
    use:"Bots, slash commands, webhooks, guild management.",
    ep:{m:"POST", u:"https://discord.com/api/v10/channels/<CHANNEL_ID>/messages", h:{"content-type":"application/json"}, b:{content:"Hello"}},
    docs:"https://discord.com/developers/docs" },
  { id:"slack", n:"Slack Web API", cat:"comm", cc:"US", tier:"free",
    auth:{t:"bearer"}, quota:"Free — app rate limits",
    use:"Post messages, manage channels, build workflows.",
    ep:{m:"POST", u:"https://slack.com/api/chat.postMessage", h:{"content-type":"application/json"}, b:{channel:"#general",text:"Hello"}},
    docs:"https://api.slack.com/web" },
  { id:"whatsapp", n:"WhatsApp Cloud API", cat:"comm", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free tier of service conversations/month",
    use:"Official WhatsApp messaging for business via Meta Graph.",
    ep:{m:"POST", u:"https://graph.facebook.com/v21.0/<PHONE_NUMBER_ID>/messages", h:{"content-type":"application/json"}, b:{messaging_product:"whatsapp",to:"<NUMBER>",type:"text",text:{body:"Hello"}}},
    docs:"https://developers.facebook.com/docs/whatsapp/cloud-api" },

  // ---------- Social & Content ----------
  { id:"youtube", n:"YouTube Data v3", cat:"social", cc:"US", tier:"free",
    auth:{t:"query"}, quota:"Free: 10,000 quota units/day",
    use:"Search videos, channels, playlists; read stats and comments.",
    ep:{m:"GET", u:"https://www.googleapis.com/youtube/v3/search?part=snippet&q=mcp&key=<YOUR_KEY>"},
    docs:"https://developers.google.com/youtube/v3" },
  { id:"reddit", n:"Reddit", cat:"social", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free: 100 QPM OAuth (commercial use paid)",
    use:"Read subreddits, posts, comments; submit content via OAuth.",
    ep:{m:"GET", u:"https://oauth.reddit.com/r/programming/hot?limit=5", h:{"User-Agent":"my-app/1.0"}},
    docs:"https://www.reddit.com/dev/api/" },
  { id:"xapi", n:"X (Twitter)", cat:"social", cc:"US", tier:"paid",
    auth:{t:"bearer"}, quota:"Free tier is write-only + tiny; real use starts $200/month",
    use:"Post and read tweets, timelines, users via v2 API.",
    ep:{m:"POST", u:"https://api.x.com/2/tweets", h:{"content-type":"application/json"}, b:{text:"Hello world"}},
    docs:"https://docs.x.com/x-api" },
  { id:"xquik", n:"Xquik", cat:"social", cc:"US", tier:"paid",
    auth:{t:"header", k:"x-api-key"}, quota:"API key required",
    use:"X/Twitter search, profile reads, follower exports, media tools, monitors and webhooks.",
    ep:{m:"GET", u:"https://xquik.com/api/v1/x/tweets/search?q=mcp"},
    docs:"https://docs.xquik.com/api-reference/overview" },
  { id:"spotify", n:"Spotify Web API", cat:"social", cc:"SE", tier:"free",
    auth:{t:"bearer"}, quota:"Free — OAuth app, rate-limited",
    use:"Search tracks, control playback, read playlists and audio features.",
    ep:{m:"GET", u:"https://api.spotify.com/v1/search?q=daft+punk&type=track&limit=1"},
    docs:"https://developer.spotify.com/documentation/web-api" },
  { id:"twitch", n:"Twitch Helix", cat:"social", cc:"US", tier:"free",
    auth:{t:"bearer"}, quota:"Free — OAuth app (also needs Client-Id header)",
    use:"Live streams, channels, clips, chat data.",
    ep:{m:"GET", u:"https://api.twitch.tv/helix/streams?first=5", h:{"Client-Id":"<CLIENT_ID>"}},
    docs:"https://dev.twitch.tv/docs/api/" },
  { id:"tmdb", n:"TMDB", cat:"social", cc:"US", tier:"free",
    auth:{t:"bearer"}, quota:"Free for non-commercial",
    use:"Movies & TV metadata, posters, ratings, trending.",
    ep:{m:"GET", u:"https://api.themoviedb.org/3/search/movie?query=inception"},
    docs:"https://developer.themoviedb.org/docs" },
  { id:"omdb", n:"OMDb", cat:"social", cc:null, tier:"freemium",
    auth:{t:"query"}, quota:"Free: 1,000 req/day",
    use:"IMDb-style movie data by title or ID.",
    ep:{m:"GET", u:"https://www.omdbapi.com/?t=Inception&apikey=<YOUR_KEY>"},
    docs:"https://www.omdbapi.com" },
  { id:"rawg", n:"RAWG Video Games", cat:"social", cc:null, tier:"free",
    auth:{t:"query"}, quota:"Free key: 20k req/month",
    use:"500k+ video games — ratings, platforms, screenshots.",
    ep:{m:"GET", u:"https://api.rawg.io/api/games?key=<YOUR_KEY>&search=zelda"},
    docs:"https://rawg.io/apidocs" },
  { id:"giphy", n:"GIPHY", cat:"social", cc:"US", tier:"freemium",
    auth:{t:"query"}, quota:"Free beta key, rate-limited",
    use:"GIF search, trending and stickers.",
    ep:{m:"GET", u:"https://api.giphy.com/v1/gifs/search?api_key=<YOUR_KEY>&q=cat"},
    docs:"https://developers.giphy.com/docs/api" },
  { id:"unsplash", n:"Unsplash", cat:"social", cc:"CA", tier:"freemium",
    auth:{t:"query"}, quota:"Free demo: 50 req/hour",
    use:"High-quality free photos with search and collections.",
    ep:{m:"GET", u:"https://api.unsplash.com/search/photos?query=mountains&client_id=<YOUR_KEY>"},
    docs:"https://unsplash.com/documentation" },

  // ---------- Images & Media ----------
  { id:"pexels", n:"Pexels", cat:"media", cc:"DE", tier:"free",
    auth:{t:"header", k:"Authorization"}, quota:"Free: 200 req/hour",
    use:"Free stock photos and videos with simple search.",
    ep:{m:"GET", u:"https://api.pexels.com/v1/search?query=nature&per_page=3"},
    docs:"https://www.pexels.com/api/documentation/" },
  { id:"pixabay", n:"Pixabay", cat:"media", cc:"DE", tier:"free",
    auth:{t:"query"}, quota:"Free: ~100 req/min",
    use:"Royalty-free images, videos and music search.",
    ep:{m:"GET", u:"https://pixabay.com/api/?key=<YOUR_KEY>&q=flowers"},
    docs:"https://pixabay.com/api/docs/" },
  { id:"cloudinary", n:"Cloudinary", cat:"media", cc:"IL", tier:"freemium",
    auth:{t:"none"}, quota:"Free: 25 monthly credits",
    use:"Image/video upload, transformation and CDN delivery (unsigned preset shown).",
    ep:{m:"POST", u:"https://api.cloudinary.com/v1_1/<CLOUD_NAME>/image/upload", h:{"content-type":"application/json"}, b:{file:"https://example.com/pic.jpg",upload_preset:"<PRESET>"}},
    docs:"https://cloudinary.com/documentation" },
  { id:"picsum", n:"Lorem Picsum", cat:"media", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Placeholder images at any size — just an image URL.",
    ep:{m:"GET", u:"https://picsum.photos/400/300"},
    docs:"https://picsum.photos" },
  { id:"qrserver", n:"QR Server (goQR)", cat:"media", cc:"DE", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Generate or read QR codes via a simple GET.",
    ep:{m:"GET", u:"https://api.qrserver.com/v1/create-qr-code/?data=Hello&size=200x200"},
    docs:"https://goqr.me/api/" },
  { id:"dicebear", n:"DiceBear Avatars", cat:"media", cc:"DE", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Deterministic SVG/PNG avatars in 30+ styles from any seed.",
    ep:{m:"GET", u:"https://api.dicebear.com/9.x/bottts/svg?seed=claude"},
    docs:"https://www.dicebear.com/how-to-use/http-api/" },
  { id:"removebg", n:"remove.bg", cat:"media", cc:"AT", tier:"freemium",
    auth:{t:"header", k:"X-Api-Key"}, quota:"Free: 50 preview calls/month",
    use:"AI background removal for product and profile images.",
    ep:{m:"POST", u:"https://api.remove.bg/v1.0/removebg", h:{"content-type":"application/json"}, b:{image_url:"https://example.com/pic.jpg",size:"auto"}},
    docs:"https://www.remove.bg/api" },

  // ---------- Dev & Code ----------
  { id:"githubapi", n:"GitHub REST", cat:"dev", cc:"US", tier:"free",
    auth:{t:"bearer"}, quota:"Free: 5,000 req/hour authenticated",
    use:"Repos, issues, PRs, actions, code search — everything GitHub.",
    ep:{m:"GET", u:"https://api.github.com/repos/dev48v/mcp-directory"},
    docs:"https://docs.github.com/rest" },
  { id:"gitlabapi", n:"GitLab", cat:"dev", cc:"US", tier:"free",
    auth:{t:"header", k:"PRIVATE-TOKEN"}, quota:"Free tier, rate-limited",
    use:"Projects, MRs, pipelines on gitlab.com or self-hosted.",
    ep:{m:"GET", u:"https://gitlab.com/api/v4/projects?membership=true"},
    docs:"https://docs.gitlab.com/api/rest/" },
  { id:"bitbucket", n:"Bitbucket", cat:"dev", cc:"AU", tier:"free",
    auth:{t:"bearer"}, quota:"Free tier, rate-limited",
    use:"Repos, PRs and pipelines via 2.0 REST API.",
    ep:{m:"GET", u:"https://api.bitbucket.org/2.0/repositories/<WORKSPACE>"},
    docs:"https://developer.atlassian.com/cloud/bitbucket/rest/" },
  { id:"npmreg", n:"npm Registry", cat:"dev", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Package metadata, versions and download counts.",
    ep:{m:"GET", u:"https://registry.npmjs.org/react/latest"},
    docs:"https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md" },
  { id:"pypi", n:"PyPI JSON", cat:"dev", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Python package metadata and release files.",
    ep:{m:"GET", u:"https://pypi.org/pypi/requests/json"},
    docs:"https://docs.pypi.org/api/" },
  { id:"stackexchange", n:"Stack Exchange", cat:"dev", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free: 300 req/day (10k with key)",
    use:"Questions, answers and tags across Stack Overflow network.",
    ep:{m:"GET", u:"https://api.stackexchange.com/2.3/questions?order=desc&sort=activity&site=stackoverflow"},
    docs:"https://api.stackexchange.com/docs" },
  { id:"jsonplaceholder", n:"JSONPlaceholder", cat:"dev", cc:"FR", tier:"free",
    auth:{t:"none"}, quota:"Free fake REST API for prototyping",
    use:"Fake posts/users/todos endpoints for demos and tests.",
    ep:{m:"GET", u:"https://jsonplaceholder.typicode.com/posts/1"},
    docs:"https://jsonplaceholder.typicode.com" },
  { id:"httpbin", n:"httpbin", cat:"dev", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free echo/debug service",
    use:"Inspect what your HTTP client actually sends.",
    ep:{m:"GET", u:"https://httpbin.org/get?demo=1"},
    docs:"https://httpbin.org" },
  { id:"postmanecho", n:"Postman Echo", cat:"dev", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free echo service",
    use:"Test requests — echoes headers, params and body back.",
    ep:{m:"GET", u:"https://postman-echo.com/get?demo=1"},
    docs:"https://learning.postman.com/docs/developer/echo-api/" },
  { id:"cratesio", n:"crates.io", cat:"dev", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free — set a User-Agent",
    use:"Rust crate metadata, versions and downloads.",
    ep:{m:"GET", u:"https://crates.io/api/v1/crates/serde", h:{"User-Agent":"my-app/1.0"}},
    docs:"https://doc.rust-lang.org/cargo/reference/registry-web-api.html" },

  // ---------- Open Data & Science ----------
  { id:"nasa", n:"NASA APIs", cat:"data", cc:"US", tier:"free",
    auth:{t:"query"}, quota:"Free: DEMO_KEY works; 1,000 req/hour with key",
    use:"APOD, Mars rover photos, asteroids, Earth imagery.",
    ep:{m:"GET", u:"https://api.nasa.gov/planetary/apod?api_key=DEMO_KEY"},
    docs:"https://api.nasa.gov" },
  { id:"usgs", n:"USGS Earthquakes", cat:"data", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Real-time global earthquake feeds as GeoJSON.",
    ep:{m:"GET", u:"https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_day.geojson"},
    docs:"https://earthquake.usgs.gov/fdsnws/event/1/" },
  { id:"openlibrary", n:"Open Library", cat:"data", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Books, authors, covers and search from the Internet Archive.",
    ep:{m:"GET", u:"https://openlibrary.org/search.json?q=the+hobbit&limit=3"},
    docs:"https://openlibrary.org/developers/api" },
  { id:"openfoodfacts", n:"Open Food Facts", cat:"data", cc:"FR", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Nutrition facts and ingredients for 3M+ food products by barcode.",
    ep:{m:"GET", u:"https://world.openfoodfacts.org/api/v2/product/3017624010701.json"},
    docs:"https://openfoodfacts.github.io/openfoodfacts-server/api/" },
  { id:"pokeapi", n:"PokéAPI", cat:"data", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free, no key — fair use",
    use:"All Pokémon data — the classic learning API.",
    ep:{m:"GET", u:"https://pokeapi.co/api/v2/pokemon/pikachu"},
    docs:"https://pokeapi.co/docs/v2" },
  { id:"catapi", n:"The Cat API", cat:"data", cc:null, tier:"freemium",
    auth:{t:"header", k:"x-api-key"}, quota:"Free: 10k req/month",
    use:"Random cat images, breeds and votes (dogs too — same API family).",
    ep:{m:"GET", u:"https://api.thecatapi.com/v1/images/search?limit=3"},
    docs:"https://thecatapi.com" },
  { id:"spacex", n:"SpaceX API (community)", cat:"data", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Launches, rockets and Starlink data (community-maintained).",
    ep:{m:"GET", u:"https://api.spacexdata.com/v5/launches/latest"},
    docs:"https://github.com/r-spacex/SpaceX-API" },
  { id:"worldbank", n:"World Bank", cat:"data", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"GDP, population and 16k development indicators by country.",
    ep:{m:"GET", u:"https://api.worldbank.org/v2/country/IN/indicator/NY.GDP.MKTP.CD?format=json&date=2023"},
    docs:"https://datahelpdesk.worldbank.org/knowledgebase/topics/125589" },
  { id:"arxivapi", n:"arXiv", cat:"data", cc:"US", tier:"free",
    auth:{t:"none"}, quota:"Free — 1 req/3s courtesy",
    use:"Search research paper metadata and abstracts (Atom XML).",
    ep:{m:"GET", u:"http://export.arxiv.org/api/query?search_query=all:model+context+protocol&max_results=3"},
    docs:"https://info.arxiv.org/help/api/index.html" },

  // ---------- Storage & BaaS ----------
  { id:"supabaseapi", n:"Supabase", cat:"store", cc:"US", tier:"freemium",
    auth:{t:"header", k:"apikey"}, quota:"Free: 500MB DB, 2 projects",
    use:"Instant REST over Postgres + auth + storage + realtime.",
    ep:{m:"GET", u:"https://<PROJECT>.supabase.co/rest/v1/todos?select=*"},
    docs:"https://supabase.com/docs/guides/api" },
  { id:"firestore", n:"Firebase Firestore REST", cat:"store", cc:"US", tier:"freemium",
    auth:{t:"none"}, quota:"Free Spark plan: 1GB, 50k reads/day",
    use:"Document database reads/writes over REST.",
    ep:{m:"GET", u:"https://firestore.googleapis.com/v1/projects/<PROJECT_ID>/databases/(default)/documents/<COLLECTION>"},
    docs:"https://firebase.google.com/docs/firestore/use-rest-api" },
  { id:"s3", n:"AWS S3", cat:"store", cc:"US", tier:"freemium",
    auth:{t:"none"}, quota:"Free tier: 5GB for 12 months",
    use:"Object storage — the default for files at any scale (SigV4-signed requests; use an SDK).",
    ep:null,
    docs:"https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html" },
  { id:"airtableapi", n:"Airtable", cat:"store", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free: 1,000 records/base, 5 req/sec",
    use:"Spreadsheet-database records over clean REST.",
    ep:{m:"GET", u:"https://api.airtable.com/v0/<BASE_ID>/<TABLE>?maxRecords=3"},
    docs:"https://airtable.com/developers/web/api/introduction" },
  { id:"notionapi", n:"Notion", cat:"store", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free — 3 req/sec",
    use:"Pages, databases and blocks as an API-backed workspace.",
    ep:{m:"POST", u:"https://api.notion.com/v1/search", h:{"Notion-Version":"2022-06-28","content-type":"application/json"}, b:{query:"roadmap"}},
    docs:"https://developers.notion.com" },
  { id:"gsheets", n:"Google Sheets", cat:"store", cc:"US", tier:"free",
    auth:{t:"query"}, quota:"Free: 300 read req/min per project",
    use:"Read/write spreadsheet cells — the everyman database.",
    ep:{m:"GET", u:"https://sheets.googleapis.com/v4/spreadsheets/<SHEET_ID>/values/Sheet1!A1:B5?key=<YOUR_KEY>"},
    docs:"https://developers.google.com/sheets/api" },

  // ---------- Utilities ----------
  { id:"deepl", n:"DeepL", cat:"util", cc:"DE", tier:"freemium",
    auth:{t:"header", k:"Authorization"}, quota:"Free: 500k chars/month (header value: DeepL-Auth-Key YOUR_KEY)",
    use:"The best machine translation — 30+ languages.",
    ep:{m:"POST", u:"https://api-free.deepl.com/v2/translate", h:{"content-type":"application/json"}, b:{text:["Hello world"],target_lang:"HI"}},
    docs:"https://developers.deepl.com/docs" },
  { id:"libretranslate", n:"LibreTranslate", cat:"util", cc:null, tier:"freemium",
    auth:{t:"none"}, quota:"Self-host free; hosted needs key",
    use:"Open-source translation you can run yourself.",
    ep:{m:"POST", u:"https://libretranslate.com/translate", h:{"content-type":"application/json"}, b:{q:"Hello",source:"en",target:"hi"}},
    docs:"https://libretranslate.com/docs/" },
  { id:"ocrspace", n:"OCR.space", cat:"util", cc:"DE", tier:"freemium",
    auth:{t:"header", k:"apikey"}, quota:"Free: 25k req/month",
    use:"Extract text from images and PDFs via simple POST.",
    ep:{m:"POST", u:"https://api.ocr.space/parse/image", h:{"content-type":"application/x-www-form-urlencoded"}, b:"url=https://example.com/receipt.jpg&language=eng"},
    docs:"https://ocr.space/ocrapi" },
  { id:"bitly", n:"Bitly", cat:"util", cc:"US", tier:"freemium",
    auth:{t:"bearer"}, quota:"Free: 10 links/month",
    use:"Shorten URLs and track clicks.",
    ep:{m:"POST", u:"https://api-ssl.bitly.com/v4/shorten", h:{"content-type":"application/json"}, b:{long_url:"https://example.com"}},
    docs:"https://dev.bitly.com/api-reference/" },
  { id:"isgd", n:"is.gd", cat:"util", cc:"GB", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Zero-signup URL shortener.",
    ep:{m:"GET", u:"https://is.gd/create.php?format=json&url=https://example.com"},
    docs:"https://is.gd/apishorteningreference.php" },
  { id:"hibp", n:"Have I Been Pwned", cat:"util", cc:"AU", tier:"paid",
    auth:{t:"header", k:"hibp-api-key"}, quota:"Key from ~$4/month",
    use:"Check if an email appears in known data breaches.",
    ep:{m:"GET", u:"https://haveibeenpwned.com/api/v3/breachedaccount/test@example.com", h:{"user-agent":"my-app"}},
    docs:"https://haveibeenpwned.com/API/v3" },
  { id:"zippopotam", n:"Zippopotam.us", cat:"util", cc:null, tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Postal/ZIP code → place lookup for 60+ countries.",
    ep:{m:"GET", u:"https://api.zippopotam.us/us/90210"},
    docs:"https://www.zippopotam.us" },
  { id:"nagerdate", n:"Nager.Date", cat:"util", cc:"AT", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"Public holidays for 100+ countries.",
    ep:{m:"GET", u:"https://date.nager.at/api/v3/PublicHolidays/2026/IN"},
    docs:"https://date.nager.at/Api" },

  // ---------- India 🇮🇳 ----------
  { id:"razorpay", n:"Razorpay", cat:"india", cc:"IN", tier:"freemium",
    auth:{t:"basic"}, quota:"Free to integrate — fees per transaction (user: key_id, pass: key_secret)",
    use:"India's leading payment gateway — UPI, cards, netbanking, payouts.",
    ep:{m:"GET", u:"https://api.razorpay.com/v1/payments?count=3"},
    docs:"https://razorpay.com/docs/api/" },
  { id:"cashfree", n:"Cashfree", cat:"india", cc:"IN", tier:"freemium",
    auth:{t:"none"}, quota:"Free sandbox — fees per transaction",
    use:"Payments + payouts + UPI collection with strong API-first design.",
    ep:null,
    docs:"https://www.cashfree.com/docs/api-reference" },
  { id:"setu", n:"Setu", cat:"india", cc:"IN", tier:"paid",
    auth:{t:"none"}, quota:"Commercial — sandbox available",
    use:"UPI deeplinks, Account Aggregator, BBPS and KYC building blocks.",
    ep:null,
    docs:"https://docs.setu.co" },
  { id:"datagovin", n:"data.gov.in", cat:"india", cc:"IN", tier:"free",
    auth:{t:"query"}, quota:"Free key — government open data",
    use:"100k+ Indian government datasets — prices, AQI, census, transport.",
    ep:{m:"GET", u:"https://api.data.gov.in/resource/<RESOURCE_ID>?api-key=<YOUR_KEY>&format=json&limit=5"},
    docs:"https://data.gov.in/help/how-use-datasets-apis" },
  { id:"pincode", n:"India Post Pincode", cat:"india", cc:"IN", tier:"free",
    auth:{t:"none"}, quota:"Free, no key",
    use:"PIN code → post offices, district, state lookup.",
    ep:{m:"GET", u:"https://api.postalpincode.in/pincode/700001"},
    docs:"https://www.postalpincode.in/Api-Details" },
  { id:"digilocker", n:"DigiLocker", cat:"india", cc:"IN", tier:"free",
    auth:{t:"none"}, quota:"Free — government partner onboarding required",
    use:"Fetch verified citizen documents (Aadhaar-linked) with consent.",
    ep:null,
    docs:"https://apisetu.gov.in" },
  { id:"mappls", n:"Mappls (MapmyIndia)", cat:"india", cc:"IN", tier:"freemium",
    auth:{t:"none"}, quota:"Free tier for developers",
    use:"India-grade maps, geocoding and navigation — better local coverage.",
    ep:null,
    docs:"https://developer.mappls.com" },
  { id:"ondc", n:"ONDC", cat:"india", cc:"IN", tier:"free",
    auth:{t:"none"}, quota:"Open network — registration required",
    use:"Open e-commerce network protocol (Beckn) — sell/buy across apps.",
    ep:null,
    docs:"https://ondc.org" }
];
